<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns="http://maven.apache.org/POM/4.0.0" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>com.sap.cds</groupId>
    <artifactId>cds-feature-advanced-event-mesh-root</artifactId>
    <version>${revision}</version>
  </parent>

  <artifactId>cds-feature-advanced-event-mesh</artifactId>
  <packaging>jar</packaging>

  <name>CDS Plugin for SAP Integration Suite, Advanced Event Mesh</name>
  <url>https://cap.cloud.sap/docs/plugins/#advanced-event-mesh-plugin</url> <!-- TODO -->

  <dependencies>
    <!-- CDS DEPENDENCIES -->
    <dependency>
      <groupId>com.sap.cds</groupId>
      <artifactId>cds-services-messaging</artifactId>
    </dependency>

    <dependency>
      <groupId>com.sap.cds</groupId>
      <artifactId>cds-services-utils</artifactId>
    </dependency>

    <dependency>
      <groupId>com.sap.cloud.sdk.cloudplatform</groupId>
      <artifactId>connectivity-apache-httpclient4</artifactId>
    </dependency>

    <dependency>
      <groupId>org.apache.qpid</groupId>
      <artifactId>qpid-jms-client</artifactId>
    </dependency>

    <dependency>
      <groupId>jakarta.servlet</groupId>
      <artifactId>jakarta.servlet-api</artifactId>
      <scope>provided</scope>
    </dependency>

    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-api</artifactId>
    </dependency>

    <dependency>
      <groupId>com.fasterxml.jackson.core</groupId>
      <artifactId>jackson-databind</artifactId>
    </dependency>

    <!-- JSR305 implementation for annotations like @Nonnull, @CheckReturnValue, etc. -->
    <dependency>
      <groupId>com.google.code.findbugs</groupId>
      <artifactId>jsr305</artifactId>
    </dependency>

    <!-- TEST DEPENDENCIES -->
    <dependency>
      <groupId>com.sap.cds</groupId>
      <artifactId>cds-services-impl</artifactId>
      <scope>test</scope>
    </dependency>

    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter</artifactId>
      <version>6.1.0</version>
      <scope>test</scope>
    </dependency>

    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-reload4j</artifactId>
      <version>2.0.18</version>
      <scope>test</scope>
    </dependency>

    <dependency>
      <groupId>com.jayway.jsonpath</groupId>
      <artifactId>json-path</artifactId>
      <version>3.0.0</version>
      <scope>test</scope>
    </dependency>

    <dependency>
      <groupId>org.mock-server</groupId>
      <artifactId>mockserver-netty</artifactId>
      <scope>test</scope>
      <version>7.2.0</version>
      <exclusions>
        <exclusion>
          <groupId>com.google.guava</groupId>
          <artifactId>guava</artifactId>
        </exclusion>
        <exclusion>
          <groupId>commons-io</groupId>
          <artifactId>commons-io</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
  </dependencies>

  <build>
    <finalName>${project.artifactId}</finalName>
    <plugins>

      <plugin>
        <groupId>org.pitest</groupId>
        <artifactId>pitest-maven</artifactId>
        <configuration>
          <targetClasses>
            <param>com.sap.cds.feature.messaging.aem.**</param>
          </targetClasses>
          <mutators>
            <mutator>CONSTRUCTOR_CALLS</mutator>
            <mutator>VOID_METHOD_CALLS</mutator>
            <mutator>NON_VOID_METHOD_CALLS</mutator>
            <mutator>REMOVE_CONDITIONALS_ORDER_ELSE</mutator>
            <mutator>CONDITIONALS_BOUNDARY</mutator>
            <mutator>EMPTY_RETURNS</mutator>
            <mutator>NEGATE_CONDITIONALS</mutator>
            <mutator>REMOVE_CONDITIONALS_EQUAL_IF</mutator>
            <mutator>REMOVE_CONDITIONALS_EQUAL_ELSE</mutator>
            <mutator>REMOVE_CONDITIONALS_ORDER_IF</mutator>
            <mutator>REMOVE_CONDITIONALS_ORDER_ELSE</mutator>
          </mutators>
          <coverageThreshold>95</coverageThreshold>
          <aggregatedMutationThreshold>90</aggregatedMutationThreshold>
        </configuration>

        <dependencies>
          <dependency>
            <groupId>org.pitest</groupId>
            <artifactId>pitest-junit5-plugin</artifactId>
            <version>1.2.3</version>
          </dependency>
        </dependencies>
      </plugin>

      <plugin>
        <artifactId>maven-clean-plugin</artifactId>
        <configuration>
          <filesets>
            <fileset>
              <directory>src/test/resources</directory>
              <includes>
                <include>schema.sql</include>
              </includes>
            </fileset>
            <fileset>
              <directory>src/test/resources/cds</directory>
              <includes>
                <include>csn.json</include>
              </includes>
            </fileset>
            <fileset>
              <directory>src/test/resources/gen</directory>
              <includes>
                <include>**/*</include>
              </includes>
              <followSymlinks>false</followSymlinks>
            </fileset>
            <fileset>
              <directory>./</directory>
              <includes>
                <include>.flattened-pom.xml</include>
              </includes>
            </fileset>
          </filesets>
        </configuration>
        <executions>
          <execution>
            <id>auto-clean</id>
            <phase>clean</phase>
            <goals>
              <goal>clean</goal>
            </goals>
          </execution>
        </executions>
      </plugin>

      <plugin>
        <groupId>org.jacoco</groupId>
        <artifactId>jacoco-maven-plugin</artifactId>
        <configuration>
          <excludes>
            <exclude>
              ${excluded.generation.package}**/*
            </exclude>
          </excludes>
        </configuration>
        <executions>
          <execution>
            <id>jacoco-initialize</id>
            <goals>
              <goal>prepare-agent</goal>
            </goals>
          </execution>
          <execution>
            <id>jacoco-site-report-all-tests</id>
            <phase>verify</phase>
            <goals>
              <goal>report</goal>
            </goals>
          </execution>
          <execution>
            <id>jacoco-site-report-only-unit-tests</id>
            <phase>test</phase>
            <goals>
              <goal>report</goal>
            </goals>
          </execution>
          <execution>
            <id>jacoco-check-unit-tests-only</id>
            <phase>test</phase>
            <goals>
              <goal>check</goal>
            </goals>
            <configuration>
              <rules>
                <rule implementation="org.jacoco.maven.RuleConfiguration">
                  <element>BUNDLE</element>
                  <limits>
                    <limit implementation="org.jacoco.report.check.Limit">
                      <counter>INSTRUCTION</counter>
                      <value>COVEREDRATIO</value>
                      <minimum>0.3</minimum>
                    </limit>
                    <limit implementation="org.jacoco.report.check.Limit">
                      <counter>BRANCH</counter>
                      <value>COVEREDRATIO</value>
                      <minimum>0.2</minimum>
                    </limit>
                    <limit implementation="org.jacoco.report.check.Limit">
                      <counter>COMPLEXITY</counter>
                      <value>COVEREDRATIO</value>
                      <minimum>0.3</minimum>
                    </limit>
                    <limit implementation="org.jacoco.report.check.Limit">
                      <counter>CLASS</counter>
                      <value>MISSEDCOUNT</value>
                      <maximum>4</maximum>
                    </limit>
                  </limits>
                </rule>
              </rules>
            </configuration>
          </execution>
        </executions>
      </plugin>

      <plugin>
        <artifactId>maven-javadoc-plugin</artifactId>
        <configuration>
          <skip>${skipDuringDeploy}</skip>
          <failOnError>true</failOnError>
          <doclint>all,-missing</doclint>
        </configuration>
        <executions>
          <execution>
            <goals>
              <goal>jar</goal>
            </goals>
          </execution>
        </executions>
      </plugin>

      <plugin>
        <artifactId>maven-source-plugin</artifactId>
        <executions>
          <execution>
            <goals>
              <goal>jar</goal>
            </goals>
          </execution>
        </executions>
      </plugin>

    </plugins>
  </build>

</project>
